### ISSUE TITLE
Cannot see the content when run rostopic echo /detected_object

### ISSUE THREAD

**Issue by Tranthanhbao198** [paul-shuvo/planar_pose_estimation#2]
Hello,
I am a newbie in ros. so, can you please help me explain my question? thank you
1.  I use the realsense D435 cam, but i saw that you used kinect cam, so, if i want to run this project with D435, which code in these code file i have to change to fit with D435 cam ( replace kinect cam)
2.  so, to run this project, i will have to run on 3 terminal? 1 for roscore, 1 for rosrun...... and 1 for rostopic echo.....?
thank you so much

**Comment by paul-shuvo** [comment]
This doesn't pertain to this repo, however, don't forget to change the topic names to the following as described in the `config.py` file and it should work:

```python
# Image topic for object detection
image_sub = {
    'topic': '/kinect2/qhd/image_color_rect',
    'type': Image
    }

# Pointcloud topic for retrieving
# 3D locations
pc_sub = {
    'topic': '/kinect2/qhd/points',
    'type': PointCloud2
    }
```
